// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3HqCuXJ6-JgVR8aZW0qYIebuMk44mbyQ',
    appId: '1:840673199593:web:85e6f6427761e620f7f778',
    messagingSenderId: '840673199593',
    projectId: 'my-wallet-4c9fc',
    authDomain: 'my-wallet-4c9fc.firebaseapp.com',
    storageBucket: 'my-wallet-4c9fc.firebasestorage.app',
    measurementId: 'G-3DK1SZ5KQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxg_RrbLqxLghA_H2qoK-9P1t5Z0_aYs',
    appId: '1:840673199593:android:dd9461b10a81607ff7f778',
    messagingSenderId: '840673199593',
    projectId: 'my-wallet-4c9fc',
    storageBucket: 'my-wallet-4c9fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjyLIxyx_Xeo12_p_HMsth6c85__gxwBM',
    appId: '1:840673199593:ios:dbc8ff6dd94d8c48f7f778',
    messagingSenderId: '840673199593',
    projectId: 'my-wallet-4c9fc',
    storageBucket: 'my-wallet-4c9fc.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjyLIxyx_Xeo12_p_HMsth6c85__gxwBM',
    appId: '1:840673199593:ios:dbc8ff6dd94d8c48f7f778',
    messagingSenderId: '840673199593',
    projectId: 'my-wallet-4c9fc',
    storageBucket: 'my-wallet-4c9fc.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3HqCuXJ6-JgVR8aZW0qYIebuMk44mbyQ',
    appId: '1:840673199593:web:58095aa653bd784bf7f778',
    messagingSenderId: '840673199593',
    projectId: 'my-wallet-4c9fc',
    authDomain: 'my-wallet-4c9fc.firebaseapp.com',
    storageBucket: 'my-wallet-4c9fc.firebasestorage.app',
    measurementId: 'G-MB1C8P23YP',
  );
}
